version: '3'

services:
  db:
    image: mysql:8.0.21
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: prezens_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: pass1234
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  web_api:
    container_name: prez-app
    build:
      dockerfile: Dockerfile
      context: ./prez-backend
    image: prez-app
    depends_on:
      - db
    networks:
      - default
    ports:
      - "8100:8100"
    links:
      - db

  web-app:
    container_name: prez-ui
    build: ./prez-frontend/prez-ui
    volumes:
      - './prez-ui:/prez-ui'
    ports:
      - '4200:4200'
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"

volumes:
  dbdata:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24